apiVersion: v1
factorio:
  docker:
    binaryRelativePath: /bin/x64/factorio
    factorioPath: /opt/factorio
  kubernetes:
    image: pregnor/factorio-server-docker
    imageTag: 0.16.51
    names:
      create: factorio-server-create
      log: factorio-server-log
      map: factorio-server-map
      server: factorio-server
      wait: factorio-server-wait-for-map
    namespace: factorio
    nodePort: 30000
    paths:
      configuration: /opt/persist/config
      log: /opt/persist/log
      map: /opt/persist/map
      mapIDs: /opt/persist/map/ids.log
      persist: /opt/persist
    port: 34197
    protocol: UDP
    serviceType: NodePort
  rawFiles:
  - flagName: map-gen-settings
    name: map-gen-settings.json
    path: /opt/persist/config/map-gen-settings.json
    source: config/map-gen-settings.json
    value: |-
      {
          "_comment": "Sizes can be specified as none, very-low, low, normal, high, very-high",

          "terrain_segmentation": "normal",
          "water": "normal",
          "width": 0,
          "height": 0,
          "starting_area": "normal",
          "peaceful_mode": false,

          "autoplace_controls":
          {
            "coal": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "stone": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "copper-ore": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "iron-ore": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "uranium-ore": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "crude-oil": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "trees": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "enemy-base": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "grass": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "desert": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "dirt": {"frequency": "very-high", "size": "very-high", "richness": "very-high"},
            "sand": {"frequency": "very-high", "size": "very-high", "richness": "very-high"}
          },
          "cliff_settings":
          {
            "name": "cliff",
            "cliff_elevation_0": 10,
            "cliff_elevation_interval": 10
          },

          "_comment_seed": "Use null for a random seed, number for a specific seed.",
          "seed": null
        }
  - flagName: server-settings
    name: server-settings.json
    path: /opt/persist/config/server-settings.json
    source: config/server-settings.json
    value: |-
      {
        "name": "Name of the game as it will appear in the game listing",
        "description": "Description of the game that will appear in the listing",
        "tags": [],

        "_comment_max_players": "Maximum number of players allowed, admins can join even a full server. 0 means unlimited.",
        "max_players": 0,

        "_comment_visibility": [
          "public: Game will be published on the official Factorio matching server",
          "lan: Game will be broadcast on LAN"
        ],
        "visibility": {
          "public": false,
          "lan": true
        },

        "_comment_credentials": "Your factorio.com login credentials. Required for games with visibility public",
        "username": "",
        "password": "",

        "_comment_token": "Authentication token. May be used instead of 'password' above.",
        "token": "",

        "game_password": "",

        "_comment_require_user_verification": "When set to true, the server will only allow clients that have a valid Factorio.com account",
        "require_user_verification": false,

        "_comment_max_upload_in_kilobytes_per_second": "optional, default value is 0. 0 means unlimited.",
        "max_upload_in_kilobytes_per_second": 0,

        "_comment_minimum_latency_in_ticks": "optional one tick is 16ms in default speed, default value is 0. 0 means no minimum.",
        "minimum_latency_in_ticks": 0,

        "_comment_ignore_player_limit_for_returning_players": "Players that played on this map already can join even when the max player limit was reached.",
        "ignore_player_limit_for_returning_players": true,

        "_comment_allow_commands": "possible values are, true, false and admins-only",
        "allow_commands": "admins-only",

        "_comment_autosave_interval": "Autosave interval in minutes",
        "autosave_interval": 30,

        "_comment_autosave_slots": "server autosave slots, it is cycled through when the server autosaves.",
        "autosave_slots": 6,

        "_comment_afk_autokick_interval": "How many minutes until someone is kicked when doing nothing, 0 for never.",
        "afk_autokick_interval": 0,

        "_comment_auto_pause": "Whether should the server be paused when no players are present.",
        "auto_pause": true,

        "only_admins_can_pause_the_game": true,

        "_comment_autosave_only_on_server": "Whether autosaves should be saved only on server or also on all connected clients. Default is true.",
        "autosave_only_on_server": true,

        "_comment_non_blocking_saving": "Highly experimental feature, enable only at your own risk of losing your saves. On UNIX systems, server will fork itself to create an autosave. Autosaving on connected Windows clients will be disabled regardless of autosave_only_on_server option.",
        "non_blocking_saving": false,

        "_comment_admins": "List of case insensitive usernames, that will be promoted immediately",
        "admins": []
      }
