apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.factorio.kubernetes.names.server }}
  namespace: {{ .Values.factorio.kubernetes.namespace }}
data:
{{ range .Values.factorio.rawFiles }}
{{ .name | indent 2 }}: |-
{{ .value | indent 4 }}
{{ end }}

