apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.factorio.kubernetes.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Values.factorio.kubernetes.name }}
  name: {{ .Values.factorio.kubernetes.name }}
  namespace: {{ .Values.factorio.kubernetes.namespace }}
spec:
  template:
    metadata:
      name: {{ .Values.factorio.kubernetes.name }}
      namespace: {{ .Values.factorio.kubernetes.namespace }}
      labels:
        app: {{ .Values.factorio.kubernetes.name }}
        gameID: {{ .Values.factorio.gameID }}
    spec:
      containers:
        - command:
          - /bin/bash
          - -c
          args:
          - map_id=$(cat {{ .Values.factorio.paths.mapIDs }} | tail -n 1);
            echo "Factorio map ID - $map_id";
            {{ .Values.factorio.docker.factorioPath }}{{ .Values.factorio.docker.binaryRelativePath }}
            --verbose
            --console-log {{ .Values.factorio.paths.log }}/$map_id.log
            --start-server {{ .Values.factorio.paths.map }}/$map_id.zip
            {{- range .Values.factorio.rawFiles }} --{{ .flagName }} {{ .path }}{{ end }}
          image: {{ .Values.factorio.kubernetes.image }}:{{ .Values.factorio.kubernetes.imageTag }}
          imagePullPolicy: Always
          name: {{ .Values.factorio.kubernetes.name }}
          ports:
          - name: {{ .Values.factorio.kubernetes.name }}
            containerPort: {{ .Values.factorio.kubernetes.port }}
            protocol: {{ .Values.factorio.kubernetes.protocol }}
          volumeMounts:
          - name: {{ .Values.factorio.kubernetes.name }}
            mountPath: {{ .Values.factorio.paths.configuration }}
          - name: {{ .Values.factorio.kubernetes.name }}-log
            mountPath: {{ .Values.factorio.paths.log }}
          - name: {{ .Values.factorio.kubernetes.name }}-map
            mountPath: {{ .Values.factorio.paths.map }}
      initContainers:
        - command:
          - /bin/bash
          - -c
          args:
          - sleep 10
          image: {{ .Values.factorio.kubernetes.image }}:{{ .Values.factorio.kubernetes.imageTag }}
          imagePullPolicy: Always
          name: {{ .Values.factorio.kubernetes.name }}-wait-for-map
      volumes:
      - name: {{ .Values.factorio.kubernetes.name }}
        configMap:
          name: {{ .Values.factorio.kubernetes.name }}
          items:
{{ range .Values.factorio.rawFiles }}
          - key: {{ .name }}
            path: {{ .name }}
{{ end }}
      - name: {{ .Values.factorio.kubernetes.name }}-log
        hostPath:
          path: {{ .Values.factorio.paths.log }}
          type: DirectoryOrCreate
      - name: {{ .Values.factorio.kubernetes.name }}-map
        hostPath:
          path: {{ .Values.factorio.paths.map }}
          type: DirectoryOrCreate
