apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.factorio.kubernetes.names.server }}
  name: {{ .Values.factorio.kubernetes.names.server }}
spec:
  type: {{ .Values.factorio.kubernetes.serviceType }}
  ports:
  - name: {{ .Values.factorio.kubernetes.names.server }}
    port: {{ .Values.factorio.kubernetes.port }}
    nodePort: {{ .Values.factorio.kubernetes.nodePort }}
    protocol: {{ .Values.factorio.kubernetes.protocol }}
  selector:
    app: {{ .Values.factorio.kubernetes.names.server }}
