apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.factorio.kubernetes.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.factorio.kubernetes.name }}
spec:
  type: {{ .Values.factorio.kubernetes.serviceType }}
  ports:
  - name: {{ .Values.factorio.kubernetes.name }}
    port: {{ .Values.factorio.kubernetes.port }}
    nodePort: {{ .Values.factorio.kubernetes.nodePort }}
    protocol: {{ .Values.factorio.kubernetes.protocol }}
  selector:
    app: {{ .Values.factorio.kubernetes.name }}
